// <auto-generated />
using System;
using FinalTask.Models.Context;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

namespace FinalTask.Migrations
{
    [DbContext(typeof(ExamsContext))]
    partial class ExamsContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "3.1.20")
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("FinalTask.Models.Entity.Exams", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<DateTime>("DataExam")
                        .HasColumnType("datetime2");

                    b.Property<string>("DisciplineName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("Relevance")
                        .HasColumnType("bit");

                    b.Property<int>("Score")
                        .HasColumnType("int");

                    b.Property<int?>("StudentId")
                        .HasColumnType("int");

                    b.Property<int?>("TeacherId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("StudentId");

                    b.HasIndex("TeacherId");

                    b.ToTable("Exams");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            DataExam = new DateTime(2021, 11, 24, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            DisciplineName = "Математика",
                            Relevance = true,
                            Score = 75,
                            StudentId = 1,
                            TeacherId = 1
                        },
                        new
                        {
                            Id = 2,
                            DataExam = new DateTime(2021, 11, 29, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            DisciplineName = "Математика",
                            Relevance = true,
                            Score = 90,
                            StudentId = 2,
                            TeacherId = 1
                        },
                        new
                        {
                            Id = 3,
                            DataExam = new DateTime(2021, 11, 7, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            DisciplineName = "Литература",
                            Relevance = true,
                            Score = 60,
                            StudentId = 3,
                            TeacherId = 2
                        },
                        new
                        {
                            Id = 4,
                            DataExam = new DateTime(2021, 11, 9, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            DisciplineName = "Литература",
                            Relevance = true,
                            Score = 75,
                            StudentId = 4,
                            TeacherId = 2
                        },
                        new
                        {
                            Id = 5,
                            DataExam = new DateTime(2021, 11, 7, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            DisciplineName = "Физика",
                            Relevance = true,
                            Score = 75,
                            StudentId = 5,
                            TeacherId = 3
                        },
                        new
                        {
                            Id = 6,
                            DataExam = new DateTime(2021, 11, 9, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            DisciplineName = "Физика",
                            Relevance = true,
                            Score = 80,
                            StudentId = 6,
                            TeacherId = 3
                        },
                        new
                        {
                            Id = 7,
                            DataExam = new DateTime(2021, 11, 11, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            DisciplineName = "Право",
                            Relevance = true,
                            Score = 80,
                            StudentId = 7,
                            TeacherId = 4
                        },
                        new
                        {
                            Id = 8,
                            DataExam = new DateTime(2021, 11, 11, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            DisciplineName = "Право",
                            Relevance = true,
                            Score = 75,
                            StudentId = 8,
                            TeacherId = 4
                        },
                        new
                        {
                            Id = 9,
                            DataExam = new DateTime(2021, 11, 12, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            DisciplineName = "Английский язык",
                            Relevance = true,
                            Score = 89,
                            StudentId = 9,
                            TeacherId = 5
                        },
                        new
                        {
                            Id = 10,
                            DataExam = new DateTime(2021, 11, 14, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            DisciplineName = "Английский язык",
                            Relevance = true,
                            Score = 74,
                            StudentId = 10,
                            TeacherId = 5
                        },
                        new
                        {
                            Id = 11,
                            DataExam = new DateTime(2021, 11, 16, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            DisciplineName = "Русский язык",
                            Relevance = true,
                            Score = 74,
                            StudentId = 1,
                            TeacherId = 6
                        },
                        new
                        {
                            Id = 12,
                            DataExam = new DateTime(2021, 11, 18, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            DisciplineName = "Русский язык",
                            Relevance = true,
                            Score = 90,
                            StudentId = 2,
                            TeacherId = 6
                        },
                        new
                        {
                            Id = 13,
                            DataExam = new DateTime(2021, 11, 21, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            DisciplineName = "История",
                            Relevance = true,
                            Score = 75,
                            StudentId = 3,
                            TeacherId = 7
                        },
                        new
                        {
                            Id = 14,
                            DataExam = new DateTime(2021, 11, 22, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            DisciplineName = "Философия",
                            Relevance = true,
                            Score = 80,
                            StudentId = 4,
                            TeacherId = 7
                        },
                        new
                        {
                            Id = 15,
                            DataExam = new DateTime(2021, 11, 15, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            DisciplineName = "Физическая культура",
                            Relevance = true,
                            Score = 94,
                            StudentId = 5,
                            TeacherId = 8
                        },
                        new
                        {
                            Id = 16,
                            DataExam = new DateTime(2021, 11, 16, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            DisciplineName = "Физическая культура",
                            Relevance = true,
                            Score = 91,
                            StudentId = 6,
                            TeacherId = 8
                        },
                        new
                        {
                            Id = 17,
                            DataExam = new DateTime(2021, 11, 23, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            DisciplineName = "История",
                            Relevance = true,
                            Score = 75,
                            StudentId = 7,
                            TeacherId = 9
                        },
                        new
                        {
                            Id = 18,
                            DataExam = new DateTime(2021, 11, 23, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            DisciplineName = "Философия",
                            Relevance = true,
                            Score = 80,
                            StudentId = 8,
                            TeacherId = 9
                        },
                        new
                        {
                            Id = 19,
                            DataExam = new DateTime(2021, 11, 25, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            DisciplineName = "Физика",
                            Relevance = true,
                            Score = 90,
                            StudentId = 9,
                            TeacherId = 10
                        },
                        new
                        {
                            Id = 20,
                            DataExam = new DateTime(2021, 11, 28, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            DisciplineName = "Математика",
                            Relevance = true,
                            Score = 74,
                            StudentId = 10,
                            TeacherId = 10
                        });
                });

            modelBuilder.Entity("FinalTask.Models.Entity.Students", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("Address")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Passport")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Patronymic")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Photo")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("Relevance")
                        .HasColumnType("bit");

                    b.Property<string>("SurName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("Year")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.ToTable("Students");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Address = "ул. Мира, д. 1, кв. 42",
                            Name = "Иван",
                            Passport = "ВК864157",
                            Patronymic = "Евгеньевич",
                            Photo = "student1.jpg",
                            Relevance = true,
                            SurName = "Коралев",
                            Year = 2002
                        },
                        new
                        {
                            Id = 2,
                            Address = "ул. Мира, д. 51, кв. 5",
                            Name = "Сергей",
                            Passport = "ВН214786",
                            Patronymic = "Аркадьевич",
                            Photo = "student2.jpg",
                            Relevance = true,
                            SurName = "Викторов",
                            Year = 2003
                        },
                        new
                        {
                            Id = 3,
                            Address = "ул. Артема, д. 269, кв. 1",
                            Name = "Виктор",
                            Passport = "НЕ314796",
                            Patronymic = "Ярославович",
                            Photo = "student3.jpg",
                            Relevance = true,
                            SurName = "Комаров",
                            Year = 2003
                        },
                        new
                        {
                            Id = 4,
                            Address = "ул. Ватутина, д. 3б, кв. 24",
                            Name = "Андрей",
                            Passport = "НК639852",
                            Patronymic = "Дмитриевич",
                            Photo = "student4.jpg",
                            Relevance = true,
                            SurName = "Кружкин",
                            Year = 2003
                        },
                        new
                        {
                            Id = 5,
                            Address = "ул. Ленина, д. 28а, кв. 99",
                            Name = "Геннадий",
                            Passport = "КН545821",
                            Patronymic = "Генадьевич",
                            Photo = "student5.jpg",
                            Relevance = true,
                            SurName = "Легасов",
                            Year = 2002
                        },
                        new
                        {
                            Id = 6,
                            Address = "ул. Артема, д. 110, кв. 110",
                            Name = "Олег",
                            Passport = "АВ147852",
                            Patronymic = "Сергеевич",
                            Photo = "student6.jpg",
                            Relevance = true,
                            SurName = "Водянов",
                            Year = 2000
                        },
                        new
                        {
                            Id = 7,
                            Address = "ул. Ватутина, д. 150, кв. 1",
                            Name = "Владимир",
                            Passport = "ДН963852",
                            Patronymic = "Едуардович",
                            Photo = "student7.jpg",
                            Relevance = true,
                            SurName = "Крамченко",
                            Year = 2002
                        },
                        new
                        {
                            Id = 8,
                            Address = "ул. Щорса, д. 78, кв. 22",
                            Name = "Сергей",
                            Passport = "ВК789654",
                            Patronymic = "Андреевич",
                            Photo = "student8.jpg",
                            Relevance = true,
                            SurName = "Каприн",
                            Year = 2001
                        },
                        new
                        {
                            Id = 9,
                            Address = "ул. Мира, д. 124в, кв.34",
                            Name = "Владислав",
                            Passport = "МН657812",
                            Patronymic = "Викторович",
                            Photo = "student9.jpg",
                            Relevance = true,
                            SurName = "Мавлен",
                            Year = 2001
                        },
                        new
                        {
                            Id = 10,
                            Address = "ул. Тельмана, д. 34, кв. 7",
                            Name = "Даниил",
                            Passport = "КР159753",
                            Patronymic = "Олегович,",
                            Photo = "student10.jpg",
                            Relevance = true,
                            SurName = "Купринов",
                            Year = 2001
                        });
                });

            modelBuilder.Entity("FinalTask.Models.Entity.Teachers", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<double>("ExamFee")
                        .HasColumnType("float");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Patronymic")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Photo")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("Relevance")
                        .HasColumnType("bit");

                    b.Property<string>("SurName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Teachers");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            ExamFee = 800.0,
                            Name = "Иван",
                            Patronymic = "Дмитриевич",
                            Photo = "teacher1.jpg",
                            Relevance = true,
                            SurName = "Иванов"
                        },
                        new
                        {
                            Id = 2,
                            ExamFee = 1000.0,
                            Name = "Евгений",
                            Patronymic = "Генадьевич",
                            Photo = "teacher2.jpg",
                            Relevance = true,
                            SurName = "Петров"
                        },
                        new
                        {
                            Id = 3,
                            ExamFee = 900.0,
                            Name = "Виктор",
                            Patronymic = "Сергеевич",
                            Photo = "teacher3.jpg",
                            Relevance = true,
                            SurName = "Ахметов"
                        },
                        new
                        {
                            Id = 4,
                            ExamFee = 800.0,
                            Name = "Артем",
                            Patronymic = "Сергеевич",
                            Photo = "teacher4.jpg",
                            Relevance = true,
                            SurName = "Черышев"
                        },
                        new
                        {
                            Id = 5,
                            ExamFee = 1000.0,
                            Name = "Владимир",
                            Patronymic = "Сергеевич",
                            Photo = "teacher5.jpg",
                            Relevance = true,
                            SurName = "Дзюба"
                        },
                        new
                        {
                            Id = 6,
                            ExamFee = 900.0,
                            Name = "Андрей",
                            Patronymic = "Викторович",
                            Photo = "teacher6.jpg",
                            Relevance = true,
                            SurName = "Жирков"
                        },
                        new
                        {
                            Id = 7,
                            ExamFee = 500.0,
                            Name = "Сергей",
                            Patronymic = "Олегович",
                            Photo = "teacher7.jpg",
                            Relevance = true,
                            SurName = "Павлов"
                        },
                        new
                        {
                            Id = 8,
                            ExamFee = 500.0,
                            Name = "Вадим",
                            Patronymic = "Ярославович",
                            Photo = "teacher8.jpg",
                            Relevance = true,
                            SurName = "Сереженко"
                        },
                        new
                        {
                            Id = 9,
                            ExamFee = 300.0,
                            Name = "Камил",
                            Patronymic = "Андреевич",
                            Photo = "teacher9.jpg",
                            Relevance = true,
                            SurName = "Карасев"
                        },
                        new
                        {
                            Id = 10,
                            ExamFee = 400.0,
                            Name = "Дмитрий",
                            Patronymic = "Дмитриевич",
                            Photo = "teacher10.jpg",
                            Relevance = true,
                            SurName = "Басов"
                        });
                });

            modelBuilder.Entity("FinalTask.Models.Entity.Exams", b =>
                {
                    b.HasOne("FinalTask.Models.Entity.Students", "Student")
                        .WithMany("Exams")
                        .HasForeignKey("StudentId");

                    b.HasOne("FinalTask.Models.Entity.Teachers", "Teacher")
                        .WithMany("Exams")
                        .HasForeignKey("TeacherId");
                });
#pragma warning restore 612, 618
        }
    }
}
